# Ensemble Learning

## Initial Imports

In [187]:
import warnings
warnings.filterwarnings('ignore')

In [188]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [189]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from imblearn.metrics import classification_report_imbalanced
from imblearn.ensemble import BalancedRandomForestClassifier

## Read the CSV and Perform Basic Data Cleaning

In [190]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [221]:
# Create our features
X = df.drop("loan_status", axis=1)
X = pd.get_dummies(X)
# Create our target
y = df["loan_status"]

In [222]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [224]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [225]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=42, 
                                                    stratify=y)
X_train.shape

(51612, 95)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [227]:
# Create the StandardScaler instance
data_scaler = StandardScaler()

In [228]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
data_scaler.fit(X_train)

StandardScaler()

In [229]:
# Scale the training and testing data
X_train_scaled = data_scaler.transform(X_train)
X_test_scaled = data_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [230]:
# Resample the training data with the BalancedRandomForestClassifier

rf_model = BalancedRandomForestClassifier(n_estimators=100)
rf_model = rf_model.fit(X_train, y_train)

In [231]:
# Calculated the balanced accuracy score
y_predictions = rf_model.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_predictions)
acc_score

0.7796542054945188

In [232]:
# Display the confusion matrix

cm = confusion_matrix(y_test, y_predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)

cm_df

          Predicted 0  Predicted 1
Actual 0           57           30
Actual 1         1641        15477

In [233]:
# Print the imbalanced classification report

print(classification_report_imbalanced(y_test, y_predictions))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.66      0.90      0.06      0.77      0.58        87
   low_risk       1.00      0.90      0.66      0.95      0.77      0.61     17118

avg / total       0.99      0.90      0.66      0.94      0.77      0.61     17205

In [234]:
# List the features sorted in descending order by feature importance
importances = rf_model.feature_importances_

importances_sorted = sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)
importances_sorted

[(0.07741467780127995, 'total_pymnt_inv'),
 (0.07437194900565983, 'total_rec_prncp'),
 (0.05579369619053597, 'last_pymnt_amnt'),
 (0.05296168254824833, 'total_pymnt'),
 (0.046265248834280535, 'total_rec_int'),
 (0.026832478154356663, 'int_rate'),
 (0.020591145799591298, 'issue_d_Jan-2019'),
 (0.019971477911331716, 'dti'),
 (0.018052115539915585, 'max_bal_bc'),
 (0.017293418034739473, 'il_util'),
 (0.016956028772409648, 'installment'),
 (0.016792911232641726, 'out_prncp'),
 (0.016607438688889628, 'annual_inc'),
 (0.016347718716519553, 'revol_bal'),
 (0.01610246193418771, 'mo_sin_old_rev_tl_op'),
 (0.016023081325273403, 'bc_util'),
 (0.0156349991784649, 'out_prncp_inv'),
 (0.014453044203647365, 'mo_sin_old_il_acct'),
 (0.014087533205353078, 'total_il_high_credit_limit'),
 (0.014035462066192952, 'total_rev_hi_lim'),
 (0.013448444167268878, 'mths_since_rcnt_il'),
 (0.013440258496807286, 'all_util'),
 (0.01340492048798399, 'loan_amnt'),
 (0.013336415890720616, 'total_bal_il'),
 (0.01322103195088056, 'tot_hi_cred_lim'),
 (0.012997576242819654, 'mths_since_recent_inq'),
 (0.012614012014798406, 'avg_cur_bal'),
 (0.012529639372776936, 'total_bc_limit'),
 (0.012362159423210374, 'bc_open_to_buy'),
 (0.01231854848454016, 'issue_d_Mar-2019'),
 (0.012282801025876786, 'num_op_rev_tl'),
 (0.011332469143021726, 'tot_cur_bal'),
 (0.01116251338517828, 'mths_since_recent_bc'),
 (0.010722205299865353, 'num_sats'),
 (0.010375944384335643, 'total_rec_late_fee'),
 (0.009901009345358243, 'mo_sin_rcnt_rev_tl_op'),
 (0.009865684024775024, 'open_acc'),
 (0.009486852461878373, 'total_acc'),
 (0.00937956955046121, 'num_il_tl'),
 (0.009267957054543505, 'total_bal_ex_mort'),
 (0.008858957529088649, 'acc_open_past_24mths'),
 (0.008802587795009288, 'num_bc_tl'),
 (0.008735202926900922, 'mo_sin_rcnt_tl'),
 (0.008570181299621261, 'num_rev_accts'),
 (0.00801669158091823, 'open_il_24m'),
 (0.008007400189329989, 'pct_tl_nvr_dlq'),
 (0.00789043367966426, 'num_actv_rev_tl'),
 (0.007813265404249616, 'num_tl_op_past_12m'),
 (0.007675742767551891, 'inq_last_12m'),
 (0.007059803877613672, 'inq_fi'),
 (0.00700402281111071, 'mort_acc'),
 (0.006936765663852108, 'percent_bc_gt_75'),
 (0.006660285988883958, 'total_cu_tl'),
 (0.006591510280059636, 'open_rv_24m'),
 (0.006577529022183261, 'num_bc_sats'),
 (0.006232244489259314, 'num_rev_tl_bal_gt_0'),
 (0.006229890348557136, 'next_pymnt_d_May-2019'),
 (0.005877563341580267, 'issue_d_Feb-2019'),
 (0.0057293526846228845, 'num_actv_bc_tl'),
 (0.005419433848439757, 'open_act_il'),
 (0.005115628252396529, 'inq_last_6mths'),
 (0.004958321210420606, 'open_il_12m'),
 (0.004918942675095673, 'next_pymnt_d_Apr-2019'),
 (0.004894919310860185, 'tot_coll_amt'),
 (0.004195345368642888, 'open_acc_6m'),
 (0.003921068339034748, 'delinq_2yrs'),
 (0.0034777921228146126, 'num_accts_ever_120_pd'),
 (0.002771248649869277, 'open_rv_12m'),
 (0.0027433654603866526, 'verification_status_Verified'),
 (0.002139088001079861, 'application_type_Joint App'),
 (0.00176491749141575, 'home_ownership_RENT'),
 (0.001720964323473127, 'initial_list_status_w'),
 (0.0016080130440133367, 'initial_list_status_f'),
 (0.0015935210721926395, 'home_ownership_OWN'),
 (0.0015759978928378713, 'verification_status_Source Verified'),
 (0.001554291546080439, 'pub_rec_bankruptcies'),
 (0.0014520673434336728, 'home_ownership_MORTGAGE'),
 (0.001410055478455845, 'verification_status_Not Verified'),
 (0.0013917398036317912, 'application_type_Individual'),
 (0.0012649046917770905, 'pub_rec'),
 (0.00041026993203836716, 'num_tl_90g_dpd_24m'),
 (0.00017846099716386363, 'home_ownership_ANY'),
 (0.00013833100547982487, 'chargeoff_within_12_mths'),
 (7.329910828815574e-05, 'collections_12_mths_ex_med'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [235]:
# Train the Classifier
from imblearn.ensemble import EasyEnsembleClassifier
easy = EasyEnsembleClassifier(n_estimators = 100,random_state=1)
easy = easy.fit(X_train, y_train)

In [237]:
# Calculated the balanced accuracy score
y_pred_classifier = easy.predict(X_test)
acc_score = balanced_accuracy_score(y_test, y_pred_classifier)
acc_score

0.9109900447603048

In [238]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred_classifier)

array([[   76,    11],
       [  883, 16235]], dtype=int64)

In [239]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred_classifier))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.08      0.87      0.95      0.15      0.91      0.82        87
   low_risk       1.00      0.95      0.87      0.97      0.91      0.83     17118

avg / total       0.99      0.95      0.87      0.97      0.91      0.83     17205

### Final Questions

1. Which model had the best balanced accuracy score?

    Easy Ensemble Classifier 

2. Which model had the best recall score?

    Easy Ensemble Classifier (0.95)

3. Which model had the best geometric mean score?

    Easy Ensemble Classifier (0.91)

4. What are the top three features?

     (0.07741467780127995, 'total_pymnt_inv'),
     (0.07437194900565983, 'total_rec_prncp'),
     (0.05579369619053597, 'last_pymnt_amnt'),